#!/bin/sh

#
# Copyright (C) 2014 - 2016 Humboldt-Universität zu Berlin
# %
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Initializes the database if not already initialized (including creation of
# user with appropriate permissions), starts the database server (including
# waiting for the server to be available) and handles its graceful shutdown.
#
# The purpose of the script is to handle the fact that `validate.pl` does
# neither start nor shutdown the database server it needs to run.
#
# Expects `run_once.sh` to have run once.

python bootstrap_unprivileged.py &
python_db_pid=$!
echo "sleeping 10s to wait for the database server to be available"
sleep 10
# double check that the database process didn't crash in the meantime
kill -0 $python_db_pid 2> /dev/null || { echo "Database process crashed in the meantime"; exit 1; }

# `validate.config` has been generated by `bootstrap_unprivileged.py`, but can
# be regenerated (e.g. after changes) with `generate_validate_config.py` (see
# `generate_validate_config.py --help` for usage info)
perl import.pl validate.config
perl validate.pl validate.config
validate_return_code=$?
echo "validate.pl returned with code $validate_return_code"
echo "terminating python database process with PID $python_db_pid"
# travis doesn't understand kill --signal
$(which kill) -s SIGINT $python_db_pid
exit $validate_return_code
